language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t davidlin006811/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true davidlin006811/docker-react npm run test -- -- coverage
